apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mcpo-aliyun-svc
spec:
  selector:
    app: mcpo-aliyun
  ports:
    - port: {{ .Values.mcpoAliyun.service.port }}
      targetPort: {{ .Values.mcpoAliyun.service.port }}
  type: {{ .Values.mcpoAliyun.service.type }} 