namespace: mcp-demo

# 公共 Nacos 配置
nacos:
  addr: "<YOUR_NACOS_ADDR>"
  password: "<YOUR_NACOS_PASSWORD>"

mcpoAliyun:
  image:
    repository: nacos-registry.cn-hangzhou.cr.aliyuncs.com/mcp-demo/mcpo-aliyun
    tag: 1.0.1
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000
  env:
    accessKeyId: "<YOUR_ACCESS_KEY_ID>"
    accessKeySecret: "<YOUR_ACCESS_KEY_SECRET>"

openmanus:
  image:
    repository: nacos-registry.cn-hangzhou.cr.aliyuncs.com/mcp-demo/openmanus
    tag: main-e2ec8ae7-06101749
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  storage:
    size: 20Gi
    storageClass: alicloud-disk-topology-alltype 
  env:
    OPENAI_BASE_URL: "<YOUR_OPENAI_BASE_URL>"
    OPENAI_API_KEY: "sk-123456"
    MODEL_KEY: "qwen-max-latest"

# Explore 服务配置
explore:
  enabled: true
  image:
    repository: nacos-registry.cn-hangzhou.cr.aliyuncs.com/mcp-demo/mse-sync
    tag: explore
  replicaCount: 1

# Price MCP 服务配置
priceMcp:
  enabled: true
  image:
    repository: nacos-registry.cn-hangzhou.cr.aliyuncs.com/mcp-demo/mse-sync
    tag: price-mcp
  replicaCount: 1